# Site settings
title: Dallas Game Night
email: DallasGameNight@TimRayburn.net
description: "Our Mission : Provide a free and open night for board games that is kid friendly, for the love of games!"
baseurl: ""
url: "http://DallasGameNight.TimRayburn.net"
twitter_username: DallasGameNight
github_username:  DallasGameNight

# Build settings
markdown: kramdown
permalink: pretty
